### ISSUE TITLE
Responsive template: Base & CategoryList

### ISSUE THREAD

**Issue by Ramin-RX7** [Ramin-RX7/CafeMenu#134]
**_This task has to be done on `feature/responsive-template` which already exists_**

**_Note that all of these features are supposed to be in the_ `phone` _view, Please change the PC view as less as possible._**

# Base
- Navbar:
   + In phone view, the `cart` button must be directly in the navbar (and also in the expandable menu) 

- Footer:
  + Make the text bigger

- Customer login form:
   + It has to fit the screen width
   + make the form bigger and easier to access
   + put the image below the form

# Category List
- Images must be bigger, They have fit the screen width and the text has to be below them (The text also has to be fit with screen width)

**Comment by EliBabakhani** [comment]
Task done
